### ISSUE TITLE
Apply namespace selector to the check-ignore-label.gatekeeper.sh webhook

### ISSUE THREAD

**Issue by font** [gatekeeper/gatekeeper-operator#146]

**Comment by garethahealy** [comment]
@font ; presume this is to exclude core namespaces? (i.e.: `openshift-*`) should not the operator follow what gatekeeper provides and use the exempt flag?
- https://github.com/open-policy-agent/gatekeeper/blob/release-3.3/website/docs/exempt-namespaces.md#exempting-namespaces-from-the-gatekeeper-admission-webhook-using---exempt-namespace-flag

**Comment by mmirecki** [comment]
> @font ; presume this is to exclude core namespaces? (i.e.: `openshift-*`) should not the operator follow what gatekeeper provides and use the exempt flag?
> 
> * https://github.com/open-policy-agent/gatekeeper/blob/release-3.3/website/docs/exempt-namespaces.md#exempting-namespaces-from-the-gatekeeper-admission-webhook-using---exempt-namespace-flag
> * [open-policy-agent/gatekeeper#1193](https://github.com/open-policy-agent/gatekeeper/pull/1193)

The difference between this approach and what gatekeeper provides (exempt flag) is that the exempt flag is handled inside gatekeeper pods, while the namespace selector on a hook is handled by kubernetes itself. In case of a failed gatekeeper pod, we could affect the stability of the cluster, because the handling of the exempt flag would fail (this can be worked around by setting the failure policy to Ignore). If we set the ns selector on the hook, the namespace check would not even get into gk code.

**Comment by garethahealy** [comment]
@mmirecki but wont that allow for users to self exclude by labeling their namespaces to match the selector? point is highlighted here: https://github.com/open-policy-agent/gatekeeper/issues/463#issuecomment-583661607

don't you need to use both approaches? namespace selector, which matches core namespaces (openshift-*, kube-*, default) and exempt which would be for user workloads?

**Comment by font** [comment]
Yes, both approaches may need to be used. The admin deploying would need to make sure the namespace selector and exempt namespaces are working together. We could look to add that intelligence into the operator and warn when they differ.

**Comment by mmirecki** [comment]
The two approaches have to be used together. 
Maybe we should extend the check-ignore-label webhook to allow checking additional labels besides the ignore label.

**Comment by font** [comment]
Fixed by #147.
